# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json

PackageIdentifier: FOSSA.FOSSA-cli
PackageVersion: 3.8.25
Installers:
- InstallerUrl: https://github.com/fossas/fossa-cli/releases/download/v3.8.25/fossa_3.8.25_windows_amd64.zip
  Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: fossa.exe
  InstallerSha256: NOT
ManifestType: installer
ManifestVersion: 1.4.0
